INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Circuitos Elétricos e Eletrotécnica para Engenharia Mecânica', 3, 4, 'FOZ1194');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Mecânica dos Fluidos', 3, 4, 'FOZ1195');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Mecânica dos Sólidos', 3, 4, 'FOZ1196');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Processos de Usinagem', 3, 4, 'FOZ1197');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Transferência de Calor', 3, 4, 'FOZ1198');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Engenharia de Manutenção', 4, 4, 'FOZ1467');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Gestão de Inovação Tecnológica', 4, 4, 'FOZ1565');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Máquinas de Fluxo', 4, 4, 'FOZ1199');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Máquinas Térmicas', 4, 4, 'FOZ1200');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Mecanismos e Elementos de Máquinas', 4, 4, 'FOZ1201');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Medidas Eletromecânicas e Metrologia e Controle de Processos', 4, 4, 'FOZ1202');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Processos de Conformação e Fundição', 4, 4, 'FOZ1203');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Projeto de Controladores Automáticos', 4, 4, 'FOZ1641');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Refrigeração e Ar Condicionado', 4, 4, 'FOZ1619');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Teoria de Estruturas de Materiais Compósitos', 4, 4, 'FOZ1618');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Volumes Finitos', 4, 4, 'FOZ1620');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Álgebra Linear', 1, 4, 'FOZ1755');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Cálculo I', 1, 4, 'FOZ1747');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Cálculo II', 1, 4, 'FOZ1753');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Computação I', 1, 4, 'FOZ1748');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Computação II', 1, 4, 'FOZ0690');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Desenho Técnico I', 1, 4, 'FOZ1750');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Desenho Técnico II', 1, 4, 'FOZ1756');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Física I', 1, 4, 'FOZ1749');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Física II', 1, 4, 'FOZ1754');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Geometria Analítica', 1, 4, 'FOZ1103');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Laboratório de Física I', 1, 4, 'FOZ1751');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Laboratório de Física II', 1, 4, 'FOZ1758');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Química Geral e Tecnológica', 1, 4, 'FOZ1186');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Química I', 1, 4, 'FOZ1752');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Química II', 1, 4, 'FOZ1759');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Cálculo Vetorial', 2, 4, 'FOZ1188');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Processos de Soldagem', 5, 4, 'FOZ0769');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Técnicas de Redação e Metodologia Científica', 5, 4, 'FOZ1170');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Trabalho de Conclusão de Curso', 5, 4, 'FOZ1212');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Equações Diferenciais', 2, 4, 'FOZ1158');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Física II', 2, 4, 'FOZ0738');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Laboratório de Física II', 2, 4, 'FOZ1189');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Mecânica - Estática e Dinâmica', 2, 4, 'FOZ1191');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Probabilidades  e Estatística', 2, 4, 'FOZ1162');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Termodinâmica', 2, 4, 'FOZ1192');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Análise de Sistemas Dinâmicos e Vibrações', 3, 4, 'FOZ1193');
INSERT INTO `Disciplina`(`nome`, `serie`, `curso_id`, `codigo`) VALUES ('Cálculo Numérico', 3, 4, 'FOZ0990');
