/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-07-20 18:26:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import unioeste.geral.bo.Aluno;
import unioeste.geral.manager.AlunoManager;

public final class mapa_005falunos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("unioeste.geral.manager.AlunoManager");
    _jspx_imports_classes.add("unioeste.geral.bo.Aluno");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\" dir=\"ltr\">\r\n");

	String caminho = request.getContextPath();

      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>K-Lima</title>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/r/zf-5.5.2/jqc-1.11.3,dt-1.10.8/datatables.min.css\"/> \r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://cdn.datatables.net/r/zf-5.5.2/jqc-1.11.3,dt-1.10.8/datatables.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("            $('#example').dataTable();\r\n");
      out.write("\t} );\r\n");
      out.write("    </script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(caminho);
      out.write("/css/foundation.css\">    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(caminho);
      out.write("/css/app.css\">\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"off-canvas-wrapper\">\r\n");
      out.write("      <div class=\"off-canvas-wrapper-inner\" data-off-canvas-wrapper> <!-- Essa div e a de cima servem para fazer a parte do menu lateral -->\r\n");
      out.write("\r\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("#{caminho}/includes/menu.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <!-- MAIN SECTION -->\r\n");
      out.write("          <br />\r\n");
      out.write("          <br />\r\n");
      out.write("          <br />\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("              <div class=\"columns-12\">\r\n");
      out.write("                  <div id=\"map\" style=\"height: 500px\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <!--\r\n");
      out.write("    <script src=\"");
      out.print(caminho);
      out.write("/js/vendor/jquery.js\"></script>\r\n");
      out.write("    -->\r\n");
      out.write("    <script src=\"");
      out.print(caminho);
      out.write("/js/vendor/what-input.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(caminho);
      out.write("/js/vendor/foundation.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(caminho);
      out.write("/js/app.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t// For demo to fit into DataTables site builder...\r\n");
      out.write("\t$('#example')\r\n");
      out.write("\t\t.removeClass( 'display' )\r\n");
      out.write("\t\t.addClass('tdisplay');\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("            var map;\r\n");
      out.write("            var geocoder;\r\n");
      out.write("            var cluster;\r\n");
      out.write("\r\n");
      out.write("            function placeMarkers(results, status) {\r\n");
      out.write("                if (status === 'OK') {\r\n");
      out.write("                    if (results[0]) {\r\n");
      out.write("                        cluster.addMarker(new google.maps.Marker({\r\n");
      out.write("                            map: map,\r\n");
      out.write("                            position: results[0].geometry.location\r\n");
      out.write("                        }));\r\n");
      out.write("                        \r\n");
      out.write("                        cluster.fitMapToMarkers();\r\n");
      out.write("                    } else {\r\n");
      out.write("                        // window.alert('No results found');\r\n");
      out.write("                    }\r\n");
      out.write("                } else {\r\n");
      out.write("                    // window.alert('Geocoder failed: ' + status);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function init() {\r\n");
      out.write("                map = new google.maps.Map(document.getElementById('map'), {\r\n");
      out.write("                    center: {lat: -33.8688, lng: 151.2195},\r\n");
      out.write("                    zoom: 13,\r\n");
      out.write("                    mapTypeId: 'roadmap'\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                geocoder = new google.maps.Geocoder;\r\n");
      out.write("\r\n");
      out.write("                cluster = new MarkerClusterer(map, [], {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});\r\n");
      out.write("\r\n");
      out.write("                ");

                AlunoManager manager = new AlunoManager();

                List<Aluno> alunos = (ArrayList<Aluno>) request.getAttribute("alunos");

                if (alunos == null) {
                    alunos = manager.recuperarTodosAlunos();
                }                        

                for(Aluno aluno : alunos){
      out.write("\r\n");
      out.write("                    geocoder.geocode({'address': \"");
      out.print( aluno.getRua() );
      out.write(' ');
      out.print( aluno.getNumero() );
      out.write(' ');
      out.print( aluno.getCidade());
      out.write("\"}, placeMarkers);\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js\"></script>\r\n");
      out.write("    <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyC9pNbJrgjHF7S7IXPXXZVGXPFVLDUr4S8&libraries=places&callback=init\" async defer></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
