/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
<<<<<<< HEAD
 * Generated at: 2017-07-20 18:18:20 UTC
=======
 * Generated at: 2017-07-19 19:34:18 UTC
>>>>>>> 0d6f5cf9f7f8aaa7a4cb0d6376bd23748b344155
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import unioeste.geral.bo.Aluno;
import unioeste.geral.manager.AlunoManager;

public final class tabela_005fevasao_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("unioeste.geral.manager.AlunoManager");
    _jspx_imports_classes.add("unioeste.geral.bo.Aluno");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html class=\"no-js\" lang=\"en\" dir=\"ltr\">\n");

	String caminho = request.getContextPath();

      out.write("\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>K-Lima</title>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(caminho);
      out.write("/css/datatables.min.css\"/> \n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(caminho);
      out.write("/js/datatables.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\">\n");
      out.write("\t$(document).ready(function() {\n");
      out.write("            $('#example').dataTable();\n");
      out.write("\t} );\n");
      out.write("        \n");
      out.write("        function limparFiltros(){\n");
      out.write("            document.getElementById(\"aluno\").value = \"\";\n");
      out.write("            document.getElementById(\"curso\").value = \"\";\n");
      out.write("            document.getElementById(\"anoEntrada\").value = \"\";\n");
      out.write("            document.getElementById(\"anoAtual\").value = \"\";\n");
      out.write("            document.getElementById(\"situacaoAtual\").value = \"\";\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(caminho);
      out.write("/css/foundation.css\">    \n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(caminho);
      out.write("/css/app.css\">\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    \n");
      out.write("    <div class=\"off-canvas-wrapper\">\n");
      out.write("      <div class=\"off-canvas-wrapper-inner\" data-off-canvas-wrapper> <!-- Essa div e a de cima servem para fazer a parte do menu lateral -->\n");
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("#{caminho}/includes/menu.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\n");
      out.write("\n");
      out.write("          <!-- MAIN SECTION -->\n");
      out.write("          \n");
      out.write("          <div class=\"row centralizado\">\n");
      out.write("            <div class=\"medium-12 columns\" style=\"text-align: center;\">\n");
      out.write("                <h1>Alunos</h1>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          <hr />\n");
      out.write("          \n");
      out.write("          <form action=\"PesquisarAluno\" method=\"post\">\n");
      out.write("            <div class=\"row\">              \n");
      out.write("              <div class=\"medium-6 columns\">  \n");
      out.write("                  <label>Nome\n");
      out.write("                      <input id=\"aluno\" name=\"aluno\" type=\"text\" />\n");
      out.write("                  </label>\n");
      out.write("              </div>\n");
      out.write("                <div class=\"medium-6 columns\">  \n");
      out.write("                  <label>Curso\n");
      out.write("                      <input id=\"curso\" name=\"curso\" type=\"text\" />\n");
      out.write("                  </label>\n");
      out.write("                </div>                \n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"medium-4 columns\">  \n");
      out.write("                  <label>Ano Entrada\n");
      out.write("                      <input id=\"anoEntrada\" name=\"anoEntrada\" type=\"text\" />\n");
      out.write("                  </label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"medium-4 columns\">  \n");
      out.write("                  <label>Ano Atual\n");
      out.write("                      <input id=\"anoAtual\" name=\"anoAtual\" type=\"text\" />\n");
      out.write("                  </label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"medium-4 columns\">  \n");
      out.write("                  <label>Situação Atual\n");
      out.write("                      <input id=\"situacaoAtual\" name=\"situacaoAtual\" type=\"text\" />\n");
      out.write("                  </label>\n");
      out.write("                </div>                \n");
      out.write("            </div>  \n");
      out.write("              <div class=\"row\">\n");
      out.write("                  <div class=\"medium-12 columns\">\n");
      out.write("                    <input type=\"submit\" value=\"Pesquisar\" class=\"button\" style=\"width: 150px;\" />\n");
      out.write("                    <input type=\"button\" value=\"Limpar Filtros\" class=\"button\" style=\"width: 150px;\" onclick=\"limparFiltros()\" />\n");
      out.write("                  </div>\n");
      out.write("              </div>\n");
      out.write("          </form>\n");
      out.write("          \n");
      out.write("          <hr />\n");
      out.write("          \n");
      out.write("          <div class=\"row\">             \n");
      out.write("            <table id=\"example\" class=\"display\">\n");
      out.write("              <thead>\n");
      out.write("                  <tr>\n");
      out.write("                      <th>Nome</th>\n");
      out.write("                      <th>Curso</th>\n");
      out.write("                      <th>Ano Entrada</th>\n");
      out.write("                      <th>Ano Atual</th>\n");
      out.write("                      <th>Situação Atual</th>\n");
      out.write("                  </tr>\n");
      out.write("              </thead>\n");
      out.write("              <tbody>                    \n");
      out.write("                    ");

                    AlunoManager manager = new AlunoManager();
                    
                    List<Aluno> alunos = (ArrayList<Aluno>) request.getAttribute("alunos");
                    
                    if(alunos == null){
                        alunos = manager.recuperarTodosAlunos();
                    }                        
                    
                    for(Aluno aluno : alunos){
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>");
      out.print( aluno.getNome() );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( aluno.getCurso().getNome() );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( aluno.getAnoEntrada() );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( aluno.getAnoAtual());
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( aluno.getSituacaoAtual() );
      out.write("</td>                            \n");
      out.write("                        </tr> \n");
      out.write("                    ");
}
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <br/>\n");
      out.write("    <br/>\n");
      out.write("    <br/>\n");
      out.write("    <br/>\n");
      out.write("    <br/>\n");
      out.write("\n");
      out.write("    <!--\n");
      out.write("    <script src=\"");
      out.print(caminho);
      out.write("/js/vendor/jquery.js\"></script>\n");
      out.write("    -->\n");
      out.write("    <script src=\"");
      out.print(caminho);
      out.write("/js/vendor/what-input.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(caminho);
      out.write("/js/vendor/foundation.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(caminho);
      out.write("/js/app.js\"></script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("\t// For demo to fit into DataTables site builder...\n");
      out.write("\t$('#example')\n");
      out.write("\t\t.removeClass( 'display' )\n");
      out.write("\t\t.addClass('tdisplay');\n");
      out.write("    </script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
